config/routes.rb
Rails.application.routes.draw do


    get 'name/sessions'

    # Main Routes # get '/'
    root 'pairbnbs#home'

    # Other Routes
    get 'profiles', to: 'profiles#index'

    # refer to controller # method name
    resources :reservations do
      #TODO nest payment to get ../listings/reservation/:id/payment/new
      get 'payment/new'
      post 'payment/checkout'
    end
    #remove it doesnt work#



    #######

    resources :listings do
      resources :reservations, only: [:create, :new]

    end
    resources :reservations, only: [:destroy]
    resources :tags
    # Clearance authentication
    get 'home/show'
    resources :passwords, controller: 'clearance/passwords', only: [:create, :new]
    resource :session, controller: 'sessions', only: [:create]


    resources :users, only: [:create, :show, :edit, :update] do
        resources :reservations, only: [:index, :show]
        resource :password,
                 controller: 'clearance/passwords',
                 only: [:create, :edit, :update]

        # Pagination
        concern :paginatable do
            get '(page/:page)', action: :index, on: :collection, as: ''
        end

        resources :my_resources, concerns: :paginatable
    end

    get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
    delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
    get '/sign_up' => 'clearance/users#new', as: 'sign_up'
    # Facebook authentication
    get '/auth/:provider/callback' => 'sessions#create_from_omniauth'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
    belongs_to :user

    def self.create_with_omniauth(auth_hash)
        auth = Authentication.new(provider: auth_hash['provider'], uid: auth_hash['uid'], token: auth_hash['credentials']['token'])
      end

    def update_token(auth_hash)
        self.token = auth_hash['credentials']['token']
        save
    end
end

app/models/listing.rb
class Listing < ApplicationRecord
  include PgSearch
  belongs_to :user
  has_many :reservations
  has_many :listing_tags
  has_many :tags, through: :listing_tags
  mount_uploaders :images, ImageUploader
  enum roomtype: {
    undefined: "0",
    shared_room: "1",
    entire_home: "2"
  }

  pg_search_scope :search_full_text,
  :using => {
    :tsearch => { :any_word => true }
    },
     :against => {
      :title => 'A',
      :about => 'B'
    }

end

app/models/listing_tag.rb
class ListingTag < ApplicationRecord
  belongs_to :tag
  belongs_to :listing
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :reservations
  belongs_to :user

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :listing
  validates :check_in, presence: true
  validates :check_out, presence: true
  validate :check_overlapping_dates
  validate :check_no_of_guests

  def check_overlapping_dates
    if check_in.nil? || check_out.nil?
      return errors.add(:overlapping_dates, "Must input check in and check out date")
    end
    # compare this new bookings with other bookings
    listing.reservations.each do |old_reservation|
      if overlap?(self, old_reservation)
        return errors.add(:overlapping_dates, "The booking dates does not match with others")
      end
    end
  end

  def overlap?(x,y)
    (x.check_in - y.check_out) * (y.check_in - x.check_out)
  end

  def check_no_of_guests
    if self.no_of_guests > listing.no_of_guests
      errors.add(:check_no_of_guests, "Max guest no exceeded")
    end
  end

  def total_price
    price = self.listing.price
    num_dates = (check_in..check_out).to_a.length
    price * num_dates
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :listing_tags
  has_many :listings, through: :listing_tags
end

app/models/user.rb
class User < ApplicationRecord
  require 'carrierwave/orm/activerecord'

  include Clearance::User
  has_many :listings
  has_many :reservations
  has_many :authentications, :dependent => :destroy
  validates :user_name, presence: true

  mount_uploader :image, ImageUploader


  def self.create_with_auth_and_hash(authentication, auth_hash)
      user = User.create!(full_name: auth_hash["name"], email: auth_hash["extra"]["raw_info"]["email"])
      user.authentications << (authentication)
      return user
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

    def password_optional?
      true
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
      @listings = Listing.all.order('created_at ASC').paginate(page: params[:page], per_page: 9)
  end

  def new
    @listing = Listing.new
    @listings = Listing.all
  end

  def create
    @listing = current_user.listings.new(listing_params)
    if @listing.save
      flash[:success] = "Listing is successfully created!"
      @render_new_listing = " render \"_latestlist\" "
      redirect_to new_listing_path
    else
      flash[:danger] = @listing.errors.full_messages.join(', ')
      render 'new'
    end
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    @listing.update(listing_params)
    redirect_to listing_path(@listing)
  end

private
  def listing_params
    params.require(:listing).permit(:title, :price, :ratings, :about, :bathroom, :bedroom, :address, :roomtype, {images: []})
  end
end

app/controllers/payment_controller.rb
class PaymentController < ApplicationController

  def new
      @client_token = Braintree::ClientToken.generate
  end

  def checkout
    @reservation = Reservation.find(params[:reservation_id])
    a = (@reservation.listing.price) * (@reservation.check_out - @reservation.check_in).to_i

    nonce_from_the_client = params[:checkout_form][:payment_method_nonce]
    result = Braintree::Transaction.sale(
      amount: a, # this is currently hardcoded
      payment_method_nonce: nonce_from_the_client,
      options: {
      submit_for_settlement: true
      })
      if result.success?
        redirect_to :root, flash: { success: 'Transaction successful!' }
      else
        redirect_to :root, flash: { error: 'Transaction failed. Please try again.' }
      end
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def new
    @tags = Tag.new
  end

  def create
    @tags = Tag.new(tag_params)
    if @tags.save
      render 'index', notice "New tag created!"
    else
      render 'new'
  end

  def show

  end

private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  before_action :require_login, only: [:edit, :update]
  before_action :check_authorization, only: [:edit, :update]
  before_action :set_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @reservations = @user.reservations 
  end

  def create
    @user = User.new(user_params)
      if @user.save
        UserNotifierMailer.send_signup_email(@user).deliver
        redirect_to(@user, :notice => 'User created')
      else
        redirect_to root_url
      end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      flash.now[:alert] = "Something when wrong. Please try again."
      render :edit
    end
  end


  private

  def check_authorization
    unless current_user.id == params[:id].to_i #integer must be equals to integer
      redirect_to "/"
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params[:user].permit(:user_name, :full_name, :email, :password, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/name_helper.rb
module NameHelper
end

app/helpers/pairbnbs_helper.rb
module PairbnbsHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def image_for(user, options = {size: 300})
    size = options[:size]
      if user.image? == true
          image_tag(user.image.url, width: size, height: size)
      else
          image_tag '/images/default-avatar.jpg', width: size, height: size
    end
  end
end

app/views/listings/_form.html.erb
<div class="listing-form">
  <div class="row">
    <h4 class="lead">Your Listings</h4>
    <div class="col-md-4">
      <%= f.label :title, class: 'lead', style: 'font-size:15px; margin-bottom: 7px;' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="col-md-4">
      <%= f.label :about, class: 'lead', style: 'font-size:15px; margin-bottom: 7px;' %>
      <%= f.text_field :about, class: 'form-control' %>
    </div>
    <div class="col-md-4">
      <%= f.label :about, class: 'lead', style: 'font-size:15px; margin-bottom: 7px;' %>
      <%= f.text_field :about, class: 'form-control' %>
    </div>
    <div class="col-md-4">
      <%= f.label :no_of_guests, class: 'lead', style: 'font-size:15px; margin-bottom: 7px;' %>
      <%= f.number_field :no_of_guests, class: 'form-control' %>
    </div>
    <div class="col-md-4">
      <%= f.label :bedroom, class: 'lead', style: 'font-size:15px;margin-bottom: 7px; margin-top: 7px'%>
      <%= f.number_field :bedroom, class: 'form-control' %>
    </div>
    <div class="col-md-4">
      <%= f.label :roomtype, class: 'lead', style: 'font-size:15px;margin-bottom: 7px; margin-top: 7px'%>
      <%= f.select :roomtype, Listing.roomtypes, {}, { class: 'form-control' } %>
    </div>
    <div class="col-md-4">
      <%= f.label :bathroom, class: 'lead', style:  'font-size:15px;margin-bottom: 7px; margin-top: 7px'%>
      <%= f.number_field :bathroom, class: 'form-control' %>
    </div>
    <div class="col-md-4">
      <%= f.label :price, class: 'lead', style: 'font-size:15px;margin-bottom: 7px; margin-top: 7px' %>
      <%= f.number_field :price, class: 'form-control'%>
      <br>
    </div>
    <div class="col-md-4">
      <%= f.label "Image station", class: 'lead', style: 'font-size:15px;margin-bottom: 7px; margin-top: 7px' %>
      <%= f.file_field :images, multiple:true, class: 'form-control'%>

    </div>
    <div class="col-md-4" style="margin-top: 35px">
      <%= f.submit 'Create New Listing', class: 'btn btn-default'%>
    </div>
  </div>
</div>

app/views/listings/_latestlist.html.erb
<div class="container">
  <hr>
  <div class="row">
    <div class="col-md-4">
      <div class="card-img">
        <%= image_tag("gallery4.jpg", class: "img-responsive") %>
        <div class="content-wrapper">
          <h1>user_id: <%= @listing.user_id %></h1>
          <h1>price: <%= @listing.price %></h1>
          <p>No. Bedrooms:<%= @listing.bedroom %></p>
          <p>No. Bathrooms:<%= @listing.bathroom %></p>
        </div>
        </div>
        <br>
    </div>
  </div>
</div>

app/views/listings/edit.html.erb
<h1></h1>

app/views/listings/new.html.erb
<%= form_for @listing, :html => { :multipart => true } do |f| %>
<%= render partial: '/listings/form', locals: {f: f} %>
Amenities you can add:<br>
<% hidden_field_tag "listings[tag_ids][]", nil %>
<% Tag.all.each do |t| %>
<%= check_box_tag "listings[tag_ids][]", t.id, @listing.tag_ids.include?(t.id), id: dom_id(t) %>
<%= label_tag dom_id(t), t.name %><br>
<% end %>
<% end %>

<div class="newlist-container">
  <div class="row">
    <div class="col-md-4">
      <div class="card-img">
        <% if @listings != nil %>
    <% @listings.each do |listing| %>
        <%= image_tag("gallery4.jpg", class: "img-responsive") %>
        <div class="content-wrapper">
          <h1>username <%= listing.username %><h1>
          <h2>user_id: <%= listing.user_id %></h2>
          <p>price: <%= listing.price %></p>
          <p>No. Bedrooms:<%= listing.bedroom %></p>
          <p>No. Bathrooms:<%= listing.bathroom %></p>
        </div>
        </div>
        <br>

    </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/listings/show.html.erb
<div class="img-wrapper">
<% @listing.images.each do |img| %>
      <%= image_tag img %>
  <% end %>

</div>

<div class="card-img2">
  <div class="card-content2">
    <h1>Title <%= @listing.title %></h1>
    <div>
       Posted By: <%= @listing.username %>
    </div>
    <p>Description: <%= @listing.about %></p>
    <p>No of Guest: <%= @listing.no_of_guests %></p>
    <p>Price: <%= @listing.price %></p>
    <div class="booknw">
        <%= link_to "Book Now", new_listing_reservation_path(@listing), class: "btn btn-primary booknow", style: "text-transform:uppercase; width: 100%;" %>
    </div>
  </div>
</div>

app/views/payment/new.html.erb
<div class="demo-frame">
<%= form_for :checkout_form, url: reservation_payment_checkout_path, html: { id: "cardForm"} do |form| %>

    <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
    <div id="card-number" class="hosted-field"></div>

    <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
    <div id="expiration-date" class="hosted-field"></div>

    <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
    <div id="cvv" class="hosted-field"></div>

    <%= form.hidden_field "payment_method_nonce" %>

    <div class="button-container">
      <%= form.submit "Purchase", disabled: true, class: "btn btn-primary", class: "button", id: "submit-payment-btn"%>
    </div>
  <% end %>
</div>

<!-- Load the Client component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

<!-- Load the Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>

<script>
$(document).ready(function() {

  var form = document.querySelector('#cardForm');
  var submit = document.querySelector("#submit-payment-btn ");

  braintree.client.create({
    // Replace this with your own authorization.
    authorization: '<%= @client_token %>'
  }, function (clientErr, clientInstance) {
    if (clientErr) {
      // Handle error in client creation
      return;
    }

    braintree.hostedFields.create({
      client: clientInstance,
      styles: {
        'input': {
          'font-size': '14pt'
        },
        'input.invalid': {
          'color': 'red'
        },
        'input.valid': {
          'color': 'green'
        }
      },
      fields: {
        number: {
          selector: '#card-number',
          placeholder: '4111 1111 1111 1111'
        },
        cvv: {
          selector: '#cvv',
          placeholder: '123'
        },
        expirationDate: {
          selector: '#expiration-date',
          placeholder: '10/2019'
        }
      }
    }, function (hostedFieldsErr, hostedFieldsInstance) {
      if (hostedFieldsErr) {
        // Handle error in Hosted Fields creation
        return;
      }

      submit.removeAttribute('disabled');

      form.addEventListener('submit', function (event) {
        event.preventDefault();

        hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
          if (tokenizeErr) {
            // Handle error in Hosted Fields tokenization
            return;
          }

          // Put `payload.nonce` into the `payment-method-nonce` input, and then
          // submit the form. Alternatively, you could send the nonce to your server
          // with AJAX.
          document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
          form.submit();
        });
      }, false);
    });
  });

});

</script>

app/views/users/_form.html.erb
<%= form.label :full_name %>
<%= form.text_field :full_name %>
<%= form.label :user_name %>
<%= form.text_field :user_name %>
<%= form.label :email %>
<%= form.text_field :email, type: 'email' %>
<%= form.label :password %>
<%= form.password_field :password %>
<%= form.label :image %>
<%= form.file_field :image %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>
<%= form_for(@user, html: { multipart: true}) do |f| %>
<div>
    <%= f.label :user_name %>
</div>
<div>
    <%= f.text_field :user_name %>
</div>
<div>
    <%= f.text_field :full_name %>
</div>
<div>
    <%= f.text_field :email %>
</div>
<div>
    <%= f.file_field :image %>
</div>

<%= f.submit "Save Change" %>
<% end %>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">

  <h2><%= t(".title") %></h2>

  <%= form_for @user, html: { multipart: true } do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="jumbotron" style="height: 400px;">
    <div class="container">
      <h1 style="margin-left: 370px; margin-top:100px; ">Profile for <%= @user.user_name %></h1>

      <p style="margin-left: 370px;"><%= link_to "Edit", edit_user_path(@user) %></p>
    </div>
</div>

<div class="profile-container">
  <div class="container">
    <div class="img-card">
      <%= image_for(@user) %>
        <div class="profile-content">
          <h2 class="lead profile-font"><%= @user.email %></h2>
            <p class="lead"><strong>about</strong></p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam libero quae veniam. Natus maxime explicabo praesentium, asperiores deleniti nostrum dolore. Nesciunt suscipit odio, doloremque incidunt consectetur reiciendis obcaecati. Incidunt, rem?</p>
        </div>
    </div>
    </div>