config/routes.rb
Rails.application.routes.draw do


    get 'name/sessions'

    # Main Routes # get '/'
    root 'pairbnbs#home'

    # Other Routes
    get 'profiles', to: 'profiles#index'

    # refer to controller # method name
    resources :reservations do
      #TODO nest payment to get ../listings/reservation/:id/payment/new
      get 'payment/new'
      post 'payment/checkout'
    end
    #remove it doesnt work#



    #######

    resources :listings do
      resources :reservations, only: [:create, :new]

    end
    resources :reservations, only: [:destroy]
    resources :tags
    # Clearance authentication
    get 'home/show'
    resources :passwords, controller: 'clearance/passwords', only: [:create, :new]
    resource :session, controller: 'sessions', only: [:create]


    resources :users, only: [:create, :show, :edit, :update] do
        resources :reservations, only: [:index, :show]
        resource :password,
                 controller: 'clearance/passwords',
                 only: [:create, :edit, :update]

        # Pagination
        concern :paginatable do
            get '(page/:page)', action: :index, on: :collection, as: ''
        end

        resources :my_resources, concerns: :paginatable
    end

    get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
    delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
    get '/sign_up' => 'clearance/users#new', as: 'sign_up'
    # Facebook authentication
    get '/auth/:provider/callback' => 'sessions#create_from_omniauth'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :listing
  validates :check_in, presence: true
  validates :check_out, presence: true
  validate :check_overlapping_dates
  validate :check_no_of_guests

  def check_overlapping_dates
    if check_in.nil? || check_out.nil?
      return errors.add(:overlapping_dates, "Must input check in and check out date")
    end
    # compare this new bookings with other bookings
    listing.reservations.each do |old_reservation|
      if overlap?(self, old_reservation)
        return errors.add(:overlapping_dates, "The booking dates does not match with others")
      end
    end
  end

  def overlap?(x,y)
    (x.check_in - y.check_out) * (y.check_in - x.check_out)
  end

  def check_no_of_guests
    if self.no_of_guests > listing.no_of_guests
      errors.add(:check_no_of_guests, "Max guest no exceeded")
    end
  end

  def total_price
    price = self.listing.price
    num_dates = (check_in..check_out).to_a.length
    price * num_dates
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
    @reservations = Reservation.where(user_id: current_user.id)
  end

  def create
    @listing = Listing.find(params[:listing_id])
    @reservation = current_user.reservations.new(reservation_params)
    @reservation.listing_id = @listing.id
    if @reservation.save
      ReservationJob.perform_later(@reservation, @listing)
      flash[:success] = "Successfully made reservation"
      redirect_to root_path
      # payment_new_path(@reservation.id)
    else
      # @errors = @reservation.errors.full_messages
      @errors = @reservation.errors.full_messages
      render "listings/show"
    end
  end


  def show

  end

  def new
    @reservation = Reservation.new
    @listing = Listing.find(params[:listing_id])
  end

  def update

  end

  def destroy
    @reservation = Reservation.find(params[:id])
      @reservation.destroy
    respond_to do |format|
      format.html { redirect_to @reservation.user }
      format.js { @reservation_id = params[:id] }
    end
  end

private
  def reservation_params
    params.require(:reservation).permit(:rooms, :no_of_guests, :check_in, :check_out, :user_id, :listing_id)
  end

end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/destroy.js.erb
// $('#editbook-<%= @reservation_id %>').parent().parent().fadeOut(800);

app/views/reservations/index.html.erb
<div class="table-book">
  <table class="table table-hover">
    <tr>
      <th>Listing Title</th>
      <th>Rooms</th>
      <th>No. of Guests</th>
      <th>Check In</th>
      <th>Check Out</th>
      <th>Total price</th>
      <th>Payment</th>
      <th>Status</th>
    </tr>
    <% @reservations.each do |reservation| %>
    <tr>
      <td><%= link_to reservation.listing.title, reservation.listing %></td>
      <td style="text-align: center;"><%= reservation.rooms %></td>
      <td style="text-align: center;"><%= reservation.no_of_guests %></td>
      <td><%= reservation.check_in.strftime('%d %B %y') %></td>
      <td><%= reservation.check_out.strftime('%d %B %y') %></td>
      <td style="text-align: center;"><%= reservation.total_price %></td>
      <td><%= link_to "Pay Now", reservation_payment_new_path(reservation.id) %></td>
      <td><%= link_to "Cancel Reserve", reservation, id: "editbook-#{reservation.id}", method: :delete, remote: true %></td>
    </tr>
  <%end%>
  </table>
</div>


<script src="/javascripts/reservation_index.js"></script>

app/views/reservations/new.html.erb
<h1>Book ady</h1>

<%= form_for @reservation, url: listing_reservations_path(@listing) do |f| %>
  <%= f.label :rooms %>
  <%= f.number_field :rooms %>
  <%= f.label :no_of_guests %>
  <%= f.number_field :no_of_guests %>
  <%= f.label :check_in %>
  <%= f.date_field :check_in %>
  <%= f.label :check_out %>
  <%= f.date_field :check_out %>
<%= f.submit "Reserve" %>
<% end %>