config/routes.rb
Rails.application.routes.draw do


    get 'name/sessions'

    # Main Routes # get '/'
    root 'pairbnbs#home'

    # Other Routes
    get 'profiles', to: 'profiles#index'

    # refer to controller # method name
    resources :reservations do
      #TODO nest payment to get ../listings/reservation/:id/payment/new
      get 'payment/new'
      post 'payment/checkout'
    end
    #remove it doesnt work#



    #######

    resources :listings do
      resources :reservations, only: [:create, :new]

    end
    resources :reservations, only: [:destroy]
    resources :tags
    # Clearance authentication
    get 'home/show'
    resources :passwords, controller: 'clearance/passwords', only: [:create, :new]
    resource :session, controller: 'sessions', only: [:create]


    resources :users, only: [:create, :show, :edit, :update] do
        resources :reservations, only: [:index, :show]
        resource :password,
                 controller: 'clearance/passwords',
                 only: [:create, :edit, :update]

        # Pagination
        concern :paginatable do
            get '(page/:page)', action: :index, on: :collection, as: ''
        end

        resources :my_resources, concerns: :paginatable
    end

    get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
    delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
    get '/sign_up' => 'clearance/users#new', as: 'sign_up'
    # Facebook authentication
    get '/auth/:provider/callback' => 'sessions#create_from_omniauth'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
    belongs_to :user

    def self.create_with_omniauth(auth_hash)
        auth = Authentication.new(provider: auth_hash['provider'], uid: auth_hash['uid'], token: auth_hash['credentials']['token'])
      end

    def update_token(auth_hash)
        self.token = auth_hash['credentials']['token']
        save
    end
end

app/models/listing.rb
class Listing < ApplicationRecord
  include PgSearch
  belongs_to :user
  has_many :reservations
  has_many :listing_tags
  has_many :tags, through: :listing_tags
  mount_uploaders :images, ImageUploader
  enum roomtype: {
    undefined: "0",
    shared_room: "1",
    entire_home: "2"
  }

  pg_search_scope :search_full_text,
  :using => {
    :tsearch => { :any_word => true }
    },
     :against => {
      :title => 'A',
      :about => 'B'
    }

end

app/models/listing_tag.rb
class ListingTag < ApplicationRecord
  belongs_to :tag
  belongs_to :listing
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :reservations
  belongs_to :user

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :listing
  validates :check_in, presence: true
  validates :check_out, presence: true
  validate :check_overlapping_dates
  validate :check_no_of_guests

  def check_overlapping_dates
    if check_in.nil? || check_out.nil?
      return errors.add(:overlapping_dates, "Must input check in and check out date")
    end
    # compare this new bookings with other bookings
    listing.reservations.each do |old_reservation|
      if overlap?(self, old_reservation)
        return errors.add(:overlapping_dates, "The booking dates does not match with others")
      end
    end
  end

  def overlap?(x,y)
    (x.check_in - y.check_out) * (y.check_in - x.check_out)
  end

  def check_no_of_guests
    if self.no_of_guests > listing.no_of_guests
      errors.add(:check_no_of_guests, "Max guest no exceeded")
    end
  end

  def total_price
    price = self.listing.price
    num_dates = (check_in..check_out).to_a.length
    price * num_dates
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :listing_tags
  has_many :listings, through: :listing_tags
end

app/models/user.rb
class User < ApplicationRecord
  require 'carrierwave/orm/activerecord'

  include Clearance::User
  has_many :listings
  has_many :reservations
  has_many :authentications, :dependent => :destroy
  validates :user_name, presence: true

  mount_uploader :image, ImageUploader


  def self.create_with_auth_and_hash(authentication, auth_hash)
      user = User.create!(full_name: auth_hash["name"], email: auth_hash["extra"]["raw_info"]["email"])
      user.authentications << (authentication)
      return user
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

    def password_optional?
      true
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def new
    @tags = Tag.new
  end

  def create
    @tags = Tag.new(tag_params)
    if @tags.save
      render 'index', notice "New tag created!"
    else
      render 'new'
  end

  def show

  end

private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/name_helper.rb
module NameHelper
end

app/helpers/pairbnbs_helper.rb
module PairbnbsHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def image_for(user, options = {size: 300})
    size = options[:size]
      if user.image? == true
          image_tag(user.image.url, width: size, height: size)
      else
          image_tag '/images/default-avatar.jpg', width: size, height: size
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pairbnb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>

  <body>
    <!-- put navbar code here -->
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                    <i class="material-icons" style="vertical-align: middle; margin-right:5px;">room</i>PairBnb
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                      <%= link_to 'Home', root_path %>
                    </li>
                      <% if signed_out? %>
                    <li>
                      <%= link_to 'Login', sign_in_path %>
                    </li>
                    <% else %>
                    <li>
                      <%= link_to 'My Listing', new_listing_path %>
                    </li>
                    <li>
                      <%= link_to 'My Booking', user_reservations_path(user_id: current_user.id) %>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="material-icons" style="vertical-align: middle; margin-right:5px">account_circle</i><%= current_user.user_name %><span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><%= link_to 'Profile', user_path(current_user) %></li>
                        <li><a href="#">Settings</a></li>
                        <li role="separator" class="divider"></li>
                        <li><%= link_to "Sign out", sign_out_url ,method: :delete %></li>
                      </ul>
                    </li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-#{name}" %>
    <% end %>

    <%= yield %>
  </body>
</html>